name: create_artifact
on: push
env:
  ARTIFACT_NAME: artifact_example

jobs:
  create_artifact:
    - name: checkout
      uses: actions/checkout@v1
      
    - name: upload artifact
      uses: actions/upload_artifact@v1.0.0
      with:
        name: linux
        path: ./${{env.ARTIFACT_NAME}}
        
