name: complex_workflow

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Print date
        run: date

  Job2:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      - name: Print date
        run: date
  Job3:
    # The type of runner that the job will run on
    runs-on: macos-latest
    steps:
    - name: Print date
      run: date
  Job4:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [Job1, Job2, Job3]
    steps:
    - name: Print date
      run: date
